// flow-typed signature: 4764c80927a04d962454469ea29506d3
// flow-typed version: <<STUB>>/formsy-material-ui_v^0.5.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'formsy-material-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'formsy-material-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'formsy-material-ui/lib/FormsyAutoComplete' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/FormsyCheckbox' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/FormsyDate' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/FormsyRadio' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/FormsyRadioGroup' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/FormsySelect' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/FormsyText' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/FormsyTime' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/FormsyToggle' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/index' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/lib/utils' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsyAutoComplete' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsyCheckbox' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsyDate' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsyRadio' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsyRadioGroup' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsySelect' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsyText' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsyTime' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/FormsyToggle' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/index' {
  declare module.exports: any;
}

declare module 'formsy-material-ui/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'formsy-material-ui/lib/FormsyAutoComplete.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsyAutoComplete'>;
}
declare module 'formsy-material-ui/lib/FormsyCheckbox.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsyCheckbox'>;
}
declare module 'formsy-material-ui/lib/FormsyDate.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsyDate'>;
}
declare module 'formsy-material-ui/lib/FormsyRadio.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsyRadio'>;
}
declare module 'formsy-material-ui/lib/FormsyRadioGroup.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsyRadioGroup'>;
}
declare module 'formsy-material-ui/lib/FormsySelect.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsySelect'>;
}
declare module 'formsy-material-ui/lib/FormsyText.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsyText'>;
}
declare module 'formsy-material-ui/lib/FormsyTime.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsyTime'>;
}
declare module 'formsy-material-ui/lib/FormsyToggle.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/FormsyToggle'>;
}
declare module 'formsy-material-ui/lib/index.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/index'>;
}
declare module 'formsy-material-ui/lib/utils.js' {
  declare module.exports: $Exports<'formsy-material-ui/lib/utils'>;
}
declare module 'formsy-material-ui/src/FormsyAutoComplete.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsyAutoComplete'>;
}
declare module 'formsy-material-ui/src/FormsyCheckbox.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsyCheckbox'>;
}
declare module 'formsy-material-ui/src/FormsyDate.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsyDate'>;
}
declare module 'formsy-material-ui/src/FormsyRadio.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsyRadio'>;
}
declare module 'formsy-material-ui/src/FormsyRadioGroup.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsyRadioGroup'>;
}
declare module 'formsy-material-ui/src/FormsySelect.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsySelect'>;
}
declare module 'formsy-material-ui/src/FormsyText.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsyText'>;
}
declare module 'formsy-material-ui/src/FormsyTime.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsyTime'>;
}
declare module 'formsy-material-ui/src/FormsyToggle.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/FormsyToggle'>;
}
declare module 'formsy-material-ui/src/index.jsx' {
  declare module.exports: $Exports<'formsy-material-ui/src/index'>;
}
declare module 'formsy-material-ui/src/utils.js' {
  declare module.exports: $Exports<'formsy-material-ui/src/utils'>;
}
