// flow-typed signature: e099d35b05ccfbc50ab2a3cdb34930a3
// flow-typed version: <<STUB>>/formsy-react_v^0.18.1/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'formsy-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'formsy-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'formsy-react/lib/Decorator' {
  declare module.exports: any;
}

declare module 'formsy-react/lib/HOC' {
  declare module.exports: any;
}

declare module 'formsy-react/lib/main' {
  declare module.exports: any;
}

declare module 'formsy-react/lib/Mixin' {
  declare module.exports: any;
}

declare module 'formsy-react/lib/utils' {
  declare module.exports: any;
}

declare module 'formsy-react/lib/validationRules' {
  declare module.exports: any;
}

declare module 'formsy-react/src/Decorator' {
  declare module.exports: any;
}

declare module 'formsy-react/src/HOC' {
  declare module.exports: any;
}

declare module 'formsy-react/src/main' {
  declare module.exports: any;
}

declare module 'formsy-react/src/Mixin' {
  declare module.exports: any;
}

declare module 'formsy-react/src/utils' {
  declare module.exports: any;
}

declare module 'formsy-react/src/validationRules' {
  declare module.exports: any;
}

// Filename aliases
declare module 'formsy-react/lib/Decorator.js' {
  declare module.exports: $Exports<'formsy-react/lib/Decorator'>;
}
declare module 'formsy-react/lib/HOC.js' {
  declare module.exports: $Exports<'formsy-react/lib/HOC'>;
}
declare module 'formsy-react/lib/main.js' {
  declare module.exports: $Exports<'formsy-react/lib/main'>;
}
declare module 'formsy-react/lib/Mixin.js' {
  declare module.exports: $Exports<'formsy-react/lib/Mixin'>;
}
declare module 'formsy-react/lib/utils.js' {
  declare module.exports: $Exports<'formsy-react/lib/utils'>;
}
declare module 'formsy-react/lib/validationRules.js' {
  declare module.exports: $Exports<'formsy-react/lib/validationRules'>;
}
declare module 'formsy-react/src/Decorator.js' {
  declare module.exports: $Exports<'formsy-react/src/Decorator'>;
}
declare module 'formsy-react/src/HOC.js' {
  declare module.exports: $Exports<'formsy-react/src/HOC'>;
}
declare module 'formsy-react/src/main.js' {
  declare module.exports: $Exports<'formsy-react/src/main'>;
}
declare module 'formsy-react/src/Mixin.js' {
  declare module.exports: $Exports<'formsy-react/src/Mixin'>;
}
declare module 'formsy-react/src/utils.js' {
  declare module.exports: $Exports<'formsy-react/src/utils'>;
}
declare module 'formsy-react/src/validationRules.js' {
  declare module.exports: $Exports<'formsy-react/src/validationRules'>;
}
