// flow-typed signature: 7c252473f3c0976c9920fc0ff96d59b1
// flow-typed version: <<STUB>>/kouto-swiss_v^0.12.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'kouto-swiss'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'kouto-swiss' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'kouto-swiss/_docs/_js/docs' {
  declare module.exports: any;
}

declare module 'kouto-swiss/_docs/_js/jquery.min' {
  declare module.exports: any;
}

declare module 'kouto-swiss/Gruntfile' {
  declare module.exports: any;
}

declare module 'kouto-swiss/lib/kouto-swiss' {
  declare module.exports: any;
}

declare module 'kouto-swiss/lib/kouto-swiss/functions/caniuse' {
  declare module.exports: any;
}

declare module 'kouto-swiss/lib/kouto-swiss/functions/color-fallback' {
  declare module.exports: any;
}

declare module 'kouto-swiss/lib/kouto-swiss/functions/luminosity' {
  declare module.exports: any;
}

declare module 'kouto-swiss/test/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'kouto-swiss/_docs/_js/docs.js' {
  declare module.exports: $Exports<'kouto-swiss/_docs/_js/docs'>;
}
declare module 'kouto-swiss/_docs/_js/jquery.min.js' {
  declare module.exports: $Exports<'kouto-swiss/_docs/_js/jquery.min'>;
}
declare module 'kouto-swiss/Gruntfile.js' {
  declare module.exports: $Exports<'kouto-swiss/Gruntfile'>;
}
declare module 'kouto-swiss/lib/kouto-swiss.js' {
  declare module.exports: $Exports<'kouto-swiss/lib/kouto-swiss'>;
}
declare module 'kouto-swiss/lib/kouto-swiss/functions/caniuse.js' {
  declare module.exports: $Exports<'kouto-swiss/lib/kouto-swiss/functions/caniuse'>;
}
declare module 'kouto-swiss/lib/kouto-swiss/functions/color-fallback.js' {
  declare module.exports: $Exports<'kouto-swiss/lib/kouto-swiss/functions/color-fallback'>;
}
declare module 'kouto-swiss/lib/kouto-swiss/functions/luminosity.js' {
  declare module.exports: $Exports<'kouto-swiss/lib/kouto-swiss/functions/luminosity'>;
}
declare module 'kouto-swiss/test/runner.js' {
  declare module.exports: $Exports<'kouto-swiss/test/runner'>;
}
