// flow-typed signature: 27836f6d070d4693032f96ed7479105e
// flow-typed version: <<STUB>>/postcss-loader_v^0.13.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'postcss-loader/index' {
  declare module.exports: $Exports<'postcss-loader'>;
}
declare module 'postcss-loader/index.js' {
  declare module.exports: $Exports<'postcss-loader'>;
}
