// flow-typed signature: cc762e0402acf95ebe6c525b17f6c84c
// flow-typed version: <<STUB>>/postcss-mq-keyframes_v^0.3.0/flow_v0.38.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-mq-keyframes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-mq-keyframes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-mq-keyframes/gulpfile' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-mq-keyframes/gulpfile.js' {
  declare module.exports: $Exports<'postcss-mq-keyframes/gulpfile'>;
}
declare module 'postcss-mq-keyframes/index' {
  declare module.exports: $Exports<'postcss-mq-keyframes'>;
}
declare module 'postcss-mq-keyframes/index.js' {
  declare module.exports: $Exports<'postcss-mq-keyframes'>;
}
